spring:
  application:
    name: yu-ai-agent
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yu_ai_agent?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: clx740329
server:
  port: 8234
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yupi.yuaiagent.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn
# mybatis plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    #  仅在开发环节打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 逻辑删除
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值 （默认为1）
      logic-not-delete-value: 0 # 逻辑未删除值 （默认为0）
    enable-sql-runner: true
